version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: etudiants
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d etudiants"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - tp-net

  web:
    image: espoir10/web
    container_name: web
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: etudiants
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    depends_on:
      db:
        condition: service_healthy
    command: python app.py
    networks:
      - tp-net

volumes:
  pgdata:

networks:
  tp-net:
    driver: bridge

